package mx.gob.cdmx.adip.beca.model;

import java.io.Serializable;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * CatAsentamientos generated by hbm2java
 */
@Entity
@Table(name = "cat_asentamientos", schema = "mibecaparaempezar")
public class CatAsentamientos implements Serializable {
	private static final long serialVersionUID = 8414193418896490115L;
	
	private Integer idAsentamiento;
	private CatEstados catEstados;
	private CatMunicipios catMunicipios;
	private String asentamiento;
	private Integer idAsentamientoAnterior;
	private Integer idMunicipioPorEstado;
	private Integer idAsentamientoPorEdoMun;

	public CatAsentamientos() {
	}

	public CatAsentamientos(Integer idAsentamiento, String asentamiento) {
		this.idAsentamiento = idAsentamiento;
		this.asentamiento = asentamiento;
	}

	public CatAsentamientos(Integer idAsentamiento, CatEstados catEstados, CatMunicipios catMunicipios, String asentamiento,
			Integer idAsentamientoAnterior, Integer idMunicipioPorEstado, Integer idAsentamientoPorEdoMun) {
		this.idAsentamiento = idAsentamiento;
		this.catEstados = catEstados;
		this.catMunicipios = catMunicipios;
		this.asentamiento = asentamiento;
		this.idAsentamientoAnterior = idAsentamientoAnterior;
		this.idMunicipioPorEstado = idMunicipioPorEstado;
		this.idAsentamientoPorEdoMun = idAsentamientoPorEdoMun;
	}

	@Id
	@Column(name = "id_asentamiento", unique = true, nullable = false)
	public Integer getIdAsentamiento() {
		return this.idAsentamiento;
	}

	public void setIdAsentamiento(Integer idAsentamiento) {
		this.idAsentamiento = idAsentamiento;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_estado")
	public CatEstados getCatEstados() {
		return this.catEstados;
	}

	public void setCatEstados(CatEstados catEstados) {
		this.catEstados = catEstados;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_municipio")
	public CatMunicipios getCatMunicipios() {
		return this.catMunicipios;
	}

	public void setCatMunicipios(CatMunicipios catMunicipios) {
		this.catMunicipios = catMunicipios;
	}

	@Column(name = "asentamiento", nullable = false, length = 60)
	public String getAsentamiento() {
		return this.asentamiento;
	}

	public void setAsentamiento(String asentamiento) {
		this.asentamiento = asentamiento;
	}

	@Column(name = "id_asentamiento_anterior")
	public Integer getIdAsentamientoAnterior() {
		return this.idAsentamientoAnterior;
	}

	public void setIdAsentamientoAnterior(Integer idAsentamientoAnterior) {
		this.idAsentamientoAnterior = idAsentamientoAnterior;
	}

	@Column(name = "id_municipio_por_estado")
	public Integer getIdMunicipioPorEstado() {
		return this.idMunicipioPorEstado;
	}

	public void setIdMunicipioPorEstado(Integer idMunicipioPorEstado) {
		this.idMunicipioPorEstado = idMunicipioPorEstado;
	}

	@Column(name = "id_asentamiento_por_edo_mun")
	public Integer getIdAsentamientoPorEdoMun() {
		return this.idAsentamientoPorEdoMun;
	}

	public void setIdAsentamientoPorEdoMun(Integer idAsentamientoPorEdoMun) {
		this.idAsentamientoPorEdoMun = idAsentamientoPorEdoMun;
	}
}
