package mx.gob.cdmx.adip.beca.model;

import java.io.Serializable;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.Table;

/**
 * CatCodigosPostales generated by hbm2java
 */
@Entity
@Table(name = "cat_codigos_postales", schema = "mibecaparaempezar")
@NamedQueries({
		@NamedQuery(name = "CatCodigosPostales.findPorCodigoPostal", query = "SELECT NEW mx.gob.cdmx.adip.beca.commons.dto.CatCodigosPostalesDTO("
				+ "cp.idCodigoPostal,"
				+ "	cp.codigoPostal,"
				+ " ca.idAsentamiento,"
				+ " ca.asentamiento,"
				+ " cm.idMunicipio,"
				+ " cm.municipio,"
				+ "	ce.idEstado,"
				+ "	ce.estado"
				+ ")"
				+ " FROM CatCodigosPostales cp"
				+ " JOIN cp.catAsentamientos ca"
				+ " JOIN cp.catMunicipios cm"
				+ "	JOIN cp.catEstados ce"
				+ " WHERE cp.codigoPostal = :codigoPostal") 
		})
public class CatCodigosPostales implements Serializable {

	private static final long serialVersionUID = -3716832012060119320L;
	
	private int idCodigoPostal;
	private CatAsentamientos catAsentamientos;
	private CatEstados catEstados;
	private CatMunicipios catMunicipios;
	private CatTiposAsentamiento catTiposAsentamiento;
	private String codigoPostal;

	public CatCodigosPostales() {
	}

	public CatCodigosPostales(int idCodigoPostal, CatEstados catEstados, CatMunicipios catMunicipios,
			CatTiposAsentamiento catTiposAsentamiento, String codigoPostal) {
		this.idCodigoPostal = idCodigoPostal;
		this.catEstados = catEstados;
		this.catMunicipios = catMunicipios;
		this.catTiposAsentamiento = catTiposAsentamiento;
		this.codigoPostal = codigoPostal;
	}

	public CatCodigosPostales(int idCodigoPostal, CatAsentamientos catAsentamientos, CatEstados catEstados,
			CatMunicipios catMunicipios, CatTiposAsentamiento catTiposAsentamiento, String codigoPostal) {
		this.idCodigoPostal = idCodigoPostal;
		this.catAsentamientos = catAsentamientos;
		this.catEstados = catEstados;
		this.catMunicipios = catMunicipios;
		this.catTiposAsentamiento = catTiposAsentamiento;
		this.codigoPostal = codigoPostal;
	}

	@Id

	@Column(name = "id_codigo_postal", unique = true, nullable = false)
	public int getIdCodigoPostal() {
		return this.idCodigoPostal;
	}

	public void setIdCodigoPostal(int idCodigoPostal) {
		this.idCodigoPostal = idCodigoPostal;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_asentamiento")
	public CatAsentamientos getCatAsentamientos() {
		return this.catAsentamientos;
	}

	public void setCatAsentamientos(CatAsentamientos catAsentamientos) {
		this.catAsentamientos = catAsentamientos;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_estado", nullable = false)
	public CatEstados getCatEstados() {
		return this.catEstados;
	}

	public void setCatEstados(CatEstados catEstados) {
		this.catEstados = catEstados;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_municipio", nullable = false)
	public CatMunicipios getCatMunicipios() {
		return this.catMunicipios;
	}

	public void setCatMunicipios(CatMunicipios catMunicipios) {
		this.catMunicipios = catMunicipios;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_tipo_asentamiento", nullable = false)
	public CatTiposAsentamiento getCatTiposAsentamiento() {
		return this.catTiposAsentamiento;
	}

	public void setCatTiposAsentamiento(CatTiposAsentamiento catTiposAsentamiento) {
		this.catTiposAsentamiento = catTiposAsentamiento;
	}

	@Column(name = "codigo_postal", nullable = false, length = 5)
	public String getCodigoPostal() {
		return this.codigoPostal;
	}

	public void setCodigoPostal(String codigoPostal) {
		this.codigoPostal = codigoPostal;
	}

}
