package mx.gob.cdmx.adip.beca.model;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * CatEstados generated by hbm2java
 */
@Entity
@Table(name = "cat_estados", schema = "mibecaparaempezar")
public class CatEstados implements java.io.Serializable {

	private static final long serialVersionUID = 6595279992555272837L;
	
	private int idEstado;
	private String estado;
	private String cveEstado;

	public CatEstados() {
	}

	public CatEstados(int idEstado, String estado, String cveEstado) {
		this.idEstado = idEstado;
		this.estado = estado;
		this.cveEstado = cveEstado;
	}

	@Id
	@Column(name = "id_estado", unique = true, nullable = false)
	public int getIdEstado() {
		return this.idEstado;
	}

	public void setIdEstado(int idEstado) {
		this.idEstado = idEstado;
	}

	@Column(name = "estado", nullable = false, length = 40)
	public String getEstado() {
		return this.estado;
	}

	public void setEstado(String estado) {
		this.estado = estado;
	}

	@Column(name = "cve_estado", nullable = false, length = 2)
	public String getCveEstado() {
		return this.cveEstado;
	}

	public void setCveEstado(String cveEstado) {
		this.cveEstado = cveEstado;
	}
}
