package mx.gob.cdmx.adip.beca.model;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.Table;

/**
 * CatEstatus generated by hbm2java
 */
@Entity
@Table(name = "cat_estatus", schema = "mibecaparaempezar")
@NamedQueries({
	@NamedQuery(name="CatEstatus.findAll" 
			, query="SELECT NEW mx.gob.cdmx.adip.beca.commons.dto.CatEstatusDTO "
					+ "( "
					+ "c.idEstatus, "
					+ "c.descripcion "
					+ ") "
					+ "FROM CatEstatus c "
					+ "where c.vigente = true " 
					+ "and c.tutor = true "
					+ "and c.idEstatus <> 1 "
					+ " ORDER BY c.idEstatus ASC ")
	,
	@NamedQuery(name="CatEstatus.findAllEstatusTutor"	 
	, query="SELECT NEW mx.gob.cdmx.adip.beca.commons.dto.CatEstatusDTO "
			+ "( "
			+ "c.idEstatus, "
			+ "c.descripcion "
			+ ") "
			+ "FROM CatEstatus c "
			+ "where c.tutor = true and c.idEstatus <>  1 "
			+ "and c.idEstatus <> 2 "
			+ "and c.idEstatus <> 3 "
			+ "and c.idEstatus <> 7 "
			+ "and c.idEstatus <> 4 "
			+ " ORDER BY c.descripcion ASC ")
})

public class CatEstatus implements java.io.Serializable {
		
	private static final long serialVersionUID = -8493803739019289554L;
	private Integer idEstatus;
	private String descripcion;
	private Boolean vigente;
	private Boolean tutor;
	private Boolean beneficiario;

	public CatEstatus() {
	}

	public CatEstatus(Integer idEstatus, String descripcion) {
		this.idEstatus = idEstatus;
		this.descripcion = descripcion;
	}

	public CatEstatus(Integer idEstatus, String descripcion, Boolean vigente, Boolean tutor, Boolean beneficiario) {
		this.idEstatus = idEstatus;
		this.descripcion = descripcion;
		this.vigente = vigente;
		this.tutor = tutor;
		this.beneficiario = beneficiario;
	}

	@Id
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	@Column(name = "id_estatus", unique = true, nullable = false)
	public Integer getIdEstatus() {
		return this.idEstatus;
	}

	public void setIdEstatus(Integer idEstatus) {
		this.idEstatus = idEstatus;
	}

	@Column(name = "descripcion", nullable = false, length = 50)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Column(name = "vigente")
	public Boolean getVigente() {
		return this.vigente;
	}

	public void setVigente(Boolean vigente) {
		this.vigente = vigente;
	}

	@Column(name = "tutor")
	public Boolean getTutor() {
		return this.tutor;
	}

	public void setTutor(Boolean tutor) {
		this.tutor = tutor;
	}

	@Column(name = "beneficiario")
	public Boolean getBeneficiario() {
		return this.beneficiario;
	}

	public void setBeneficiario(Boolean beneficiario) {
		this.beneficiario = beneficiario;
	}

}
