package mx.gob.cdmx.adip.beca.model;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.Table;

/**
 * CatGrupoPertenece generated by hbm2java
 */
@Entity
@Table(name = "cat_grupo_pertenece", schema = "mibecaparaempezar")
@NamedQueries({
	@NamedQuery(name = "CatGrupoPertenece.findByEstatusActive" , query = "SELECT NEW mx.gob.cdmx.adip.beca.commons.dto.CatGrupoPerteneceDTO("
			+ "ctd.idGrupoPertenece,"
			+ "ctd.descripcion,"
			+ "ctd.estatus"
			+ ")"
			+ "	FROM CatGrupoPertenece ctd"
			+ "	WHERE ctd.estatus = TRUE")
})
public class CatGrupoPertenece implements java.io.Serializable {
	
	private static final long serialVersionUID = -5043527067276648725L;
	private int idGrupoPertenece;
	private String descripcion;
	private Boolean estatus;

	public CatGrupoPertenece() {
	}

	public CatGrupoPertenece(int idGrupoPertenece) {
		this.idGrupoPertenece = idGrupoPertenece;
	}

	public CatGrupoPertenece(int idGrupoPertenece, String descripcion, Boolean estatus) {
		this.idGrupoPertenece = idGrupoPertenece;
		this.descripcion = descripcion;
		this.estatus = estatus;
	}

	@Id
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	@Column(name = "id_grupo_pertenece", unique = true, nullable = false)
	public int getIdGrupoPertenece() {
		return this.idGrupoPertenece;
	}

	public void setIdGrupoPertenece(int idGrupoPertenece) {
		this.idGrupoPertenece = idGrupoPertenece;
	}

	@Column(name = "descripcion", length = 50)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Column(name = "estatus")
	public Boolean getEstatus() {
		return this.estatus;
	}

	public void setEstatus(Boolean estatus) {
		this.estatus = estatus;
	}
}
