package mx.gob.cdmx.adip.beca.model;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.Table;

/**
 * CatIdentificacionOficial generated by hbm2java
 */
@Entity
@Table(name = "cat_identificacion_oficial", schema = "mibecaparaempezar")
@NamedQueries({
	@NamedQuery(name = "CatIdentificacionOficial.findByEstatusActive", query = "SELECT NEW mx.gob.cdmx.adip.beca.commons.dto.CatIdentificacionOficialDTO("
			+ "	cio.idIdentificacion,"
			+ "	cio.descripcion,"
			+ "	cio.estatus,"
			+ "	cio.idCatLlave,"
			+ "	cio.extranjero"
			+ ")"
			+ "	FROM CatIdentificacionOficial cio"
			+ "	WHERE cio.estatus = TRUE"),
	@NamedQuery(name = "CatIdentificacionOficial.findExtranjero", query = "SELECT NEW mx.gob.cdmx.adip.beca.commons.dto.CatIdentificacionOficialDTO("
			+ "	cio.idIdentificacion,"
			+ "	cio.descripcion,"
			+ "	cio.estatus,"
			+ "	cio.idCatLlave,"
			+ "	cio.extranjero,"
			+ "	cio.mexicano"
			+ ")"
			+ "	FROM CatIdentificacionOficial cio"
			+ "	WHERE cio.estatus = TRUE"
			+ "	AND cio.extranjero = TRUE"),
	@NamedQuery(name = "CatIdentificacionOficial.findMexicano", query = "SELECT NEW mx.gob.cdmx.adip.beca.commons.dto.CatIdentificacionOficialDTO("
			+ "	cio.idIdentificacion,"
			+ "	cio.descripcion,"
			+ "	cio.estatus,"
			+ "	cio.idCatLlave,"
			+ "	cio.extranjero,"
			+ "	cio.mexicano"
			+ ")"
			+ "	FROM CatIdentificacionOficial cio"
			+ "	WHERE cio.estatus = TRUE"
			+ "	AND cio.mexicano = TRUE")
})
public class CatIdentificacionOficial implements java.io.Serializable {
	
	private static final long serialVersionUID = 682663202370286515L;
	private Integer idIdentificacion;
	private String descripcion;
	private boolean estatus;
	private Integer idCatLlave;
	private boolean extranjero;
	private boolean mexicano;

	public CatIdentificacionOficial() {
	}

	public CatIdentificacionOficial(Integer idIdentificacion, String descripcion, boolean estatus) {
		this.idIdentificacion = idIdentificacion;
		this.descripcion = descripcion;
		this.estatus = estatus;
	}

	@Id
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	@Column(name = "id_identificacion", unique = true, nullable = false)
	public Integer getIdIdentificacion() {
		return this.idIdentificacion;
	}

	public void setIdIdentificacion(Integer idIdentificacion) {
		this.idIdentificacion = idIdentificacion;
	}

	@Column(name = "descripcion", nullable = false, length = 50)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Column(name = "estatus", nullable = false)
	public boolean isEstatus() {
		return this.estatus;
	}

	public void setEstatus(boolean estatus) {
		this.estatus = estatus;
	}

	@Column(name = "id_cat_llave")
	public Integer getIdCatLlave() {
		return idCatLlave;
	}

	public void setIdCatLlave(Integer idCatLlave) {
		this.idCatLlave = idCatLlave;
	}
	@Column(name = "extranjero")
	public boolean isExtranjero() {
		return extranjero;
	}

	public void setExtranjero(boolean extranjero) {
		this.extranjero = extranjero;
	}
	@Column(name = "mexicano")
	public boolean isMexicano() {
		return mexicano;
	}

	public void setMexicano(boolean mexicano) {
		this.mexicano = mexicano;
	}

}
