package mx.gob.cdmx.adip.beca.model;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.Table;

/**
 * CatIngresosFamilia generated by hbm2java
 */
@Entity
@Table(name = "cat_ingresos_familia", schema = "mibecaparaempezar")
@NamedQueries({
	@NamedQuery(name = "CatIngresosFamilia.findByEstatusActive" , query = "SELECT NEW mx.gob.cdmx.adip.beca.commons.dto.CatIngresosFamiliaDTO("
			+ "ctd.idIngresosFamilia,"
			+ "ctd.descripcion,"
			+ "ctd.estatus"
			+ ")"
			+ "	FROM CatIngresosFamilia ctd"
			+ "	WHERE ctd.estatus = TRUE")
})
public class CatIngresosFamilia implements java.io.Serializable {

	private static final long serialVersionUID = -3822502321557870709L;
	private int idIngresosFamilia;
	private String descripcion;
	private Boolean estatus;

	public CatIngresosFamilia() {
	}

	public CatIngresosFamilia(int idIngresosFamilia) {
		this.idIngresosFamilia = idIngresosFamilia;
	}

	public CatIngresosFamilia(int idIngresosFamilia, String descripcion, Boolean estatus) {
		this.idIngresosFamilia = idIngresosFamilia;
		this.descripcion = descripcion;
		this.estatus = estatus;
	}

	@Id
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	@Column(name = "id_ingresos_familia", unique = true, nullable = false)
	public int getIdIngresosFamilia() {
		return this.idIngresosFamilia;
	}

	public void setIdIngresosFamilia(int idIngresosFamilia) {
		this.idIngresosFamilia = idIngresosFamilia;
	}

	@Column(name = "descripcion", length = 50)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Column(name = "estatus")
	public Boolean getEstatus() {
		return this.estatus;
	}

	public void setEstatus(Boolean estatus) {
		this.estatus = estatus;
	}
}
