package mx.gob.cdmx.adip.beca.model;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.Table;

/**
 * CatMaterialesDomicilio generated by hbm2java
 */
@Entity
@Table(name = "cat_materiales_domicilio", schema = "mibecaparaempezar")
@NamedQueries({
	@NamedQuery(name = "CatMaterialesDomicilio.findByEstatusActive" , query = "SELECT NEW mx.gob.cdmx.adip.beca.commons.dto.CatMaterialesDomicilioDTO("
			+ "ctd.idMaterialesDomicilio,"
			+ "ctd.descripcion,"
			+ "ctd.estatus"
			+ ")"
			+ "	FROM CatMaterialesDomicilio ctd"
			+ "	WHERE ctd.estatus = TRUE")
})
public class CatMaterialesDomicilio implements java.io.Serializable {
	private static final long serialVersionUID = -2048586449358286007L;
	private int idMaterialesDomicilio;
	private String descripcion;
	private Boolean estatus;

	public CatMaterialesDomicilio() {
	}

	public CatMaterialesDomicilio(int idMaterialesDomicilio) {
		this.idMaterialesDomicilio = idMaterialesDomicilio;
	}

	public CatMaterialesDomicilio(int idMaterialesDomicilio, String descripcion, Boolean estatus) {
		this.idMaterialesDomicilio = idMaterialesDomicilio;
		this.descripcion = descripcion;
		this.estatus = estatus;
	}

	@Id
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	@Column(name = "id_materiales_domicilio", unique = true, nullable = false)
	public int getIdMaterialesDomicilio() {
		return this.idMaterialesDomicilio;
	}

	public void setIdMaterialesDomicilio(int idMaterialesDomicilio) {
		this.idMaterialesDomicilio = idMaterialesDomicilio;
	}

	@Column(name = "descripcion", length = 50)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Column(name = "estatus")
	public Boolean getEstatus() {
		return this.estatus;
	}

	public void setEstatus(Boolean estatus) {
		this.estatus = estatus;
	}
}
