package mx.gob.cdmx.adip.beca.model;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * CatMontoApoyo generated by Antonio Alcantar Valencia
 */
@Entity
@Table(name = "cat_monto_apoyo", schema = "mibecaparaempezar")
public class CatMontoApoyo implements java.io.Serializable {
		
	private static final long serialVersionUID = -8493803739019289554L;
	private Integer idMontoApoyo;
	private Integer idNivelEducativo;
	private Integer idCicloEscolar;
	private Double monto;
	private Boolean estatus;
	private Date fechaCreacion;

	public CatMontoApoyo() {
	}

	@Id
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	@Column(name = "id_monto_apoyo", unique = true, nullable = false)
	public Integer getIdMontoApoyo() {
		return this.idMontoApoyo;
	}

	public void setIdMontoApoyo(Integer idMontoApoyo) {
		this.idMontoApoyo = idMontoApoyo;
	}

	@Column(name = "id_nivel_educativo", nullable = false)
	public Integer getIdNivelEducativo() {
		return this.idNivelEducativo;
	}

	public void setIdNivelEducativo(Integer idNivelEducativo) {
		this.idNivelEducativo = idNivelEducativo;
	}
	
	@Column(name = "id_ciclo_escolar", nullable = false)
	public Integer getIdCicloEscolar() {
		return this.idCicloEscolar;
	}

	public void setIdCicloEscolar(Integer idCicloEscolar) {
		this.idCicloEscolar = idCicloEscolar;
	}

	@Column(name = "monto", nullable = false)
	public Double getMonto() {
		return this.monto;
	}

	public void setMonto(Double monto) {
		this.monto = monto;
	}

	@Column(name = "estatus")
	public Boolean getEstatus() {
		return this.estatus;
	}

	public void setEstatus(Boolean estatus) {
		this.estatus = estatus;
	}
	
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_creacion", nullable = true)
	public Date getFechaCreacion() {
		return this.fechaCreacion;
	}

	public void setFechaCreacion(Date fechaCreacion) {
		this.fechaCreacion = fechaCreacion;
	}


}
