package mx.gob.cdmx.adip.beca.model;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * CatMotivoNoDispersion generated by Antonio Alcantar Valencia
 */
@Entity
@Table(name = "cat_motivo_no_dispersion", schema = "mibecaparaempezar")
public class CatMotivoNoDispersion implements java.io.Serializable {
		
	private static final long serialVersionUID = -8493803739019289554L;
	private Integer idMotivoNoDispersion;
	private String descripcion;
	private Boolean estatus;

	public CatMotivoNoDispersion() {
	}

	public CatMotivoNoDispersion(Integer idMotivoNoDispersion, String descripcion, Boolean estatus) {
		this.idMotivoNoDispersion = idMotivoNoDispersion;
		this.descripcion = descripcion;
		this.estatus = estatus;
	}

	@Id
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	@Column(name = "id_motivo_no_dispersion", unique = true, nullable = false)
	public Integer getIdMotivoNoDispersion() {
		return this.idMotivoNoDispersion;
	}

	public void setIdMotivoNoDispersion(Integer idMotivoNoDispersion) {
		this.idMotivoNoDispersion = idMotivoNoDispersion;
	}

	@Column(name = "descripcion", nullable = false, length = 50)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Column(name = "estatus")
	public Boolean getEstatus() {
		return this.estatus;
	}

	public void setEstatus(Boolean estatus) {
		this.estatus = estatus;
	}


}
