package mx.gob.cdmx.adip.beca.model;

import java.io.Serializable;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.Table;

/**
 * CatMunicipios generated by hbm2java
 */
@Entity
@Table(name = "cat_municipios", schema = "mibecaparaempezar")
@NamedQueries({
	@NamedQuery(name="CatMunicipios.findAll"
			, query="SELECT NEW mx.gob.cdmx.adip.beca.commons.dto.CatMunicipiosDTO "
					+ "( "
					+ "c.idMunicipio, "
					+ "c.municipio "
					+ ") "
					+ " FROM CatMunicipios c "
					+ "where c.idEstado = 9 "
					+ " and c.idMunicipio <> -1 "
					+ " ORDER BY c.municipio ASC ")
})


public class CatMunicipios implements Serializable {
	private static final long serialVersionUID = -8049994841579080645L;
	
	private Integer idMunicipio;
	private Integer idMunicipioAnterior;
	private String municipio;
	private int idEstado;
	private int idMunicipioPorEstado;

	public CatMunicipios() {
	}

	public CatMunicipios(int idMunicipio, String municipio, int idEstado, int idMunicipioPorEstado) {
		this.idMunicipio = idMunicipio;
		this.municipio = municipio;
		this.idEstado = idEstado;
		this.idMunicipioPorEstado = idMunicipioPorEstado;
	}

	public CatMunicipios(Integer idMunicipio, Integer idMunicipioAnterior, String municipio, int idEstado,
			int idMunicipioPorEstado) {
		this.idMunicipio = idMunicipio;
		this.idMunicipioAnterior = idMunicipioAnterior;
		this.municipio = municipio;
		this.idEstado = idEstado;
		this.idMunicipioPorEstado = idMunicipioPorEstado;
	}

	@Id

	@Column(name = "id_municipio", unique = true, nullable = false)
	public Integer getIdMunicipio() {
		return this.idMunicipio;
	}

	public void setIdMunicipio(Integer idMunicipio) {
		this.idMunicipio = idMunicipio;
	}

	@Column(name = "id_municipio_anterior")
	public Integer getIdMunicipioAnterior() {
		return this.idMunicipioAnterior;
	}

	public void setIdMunicipioAnterior(Integer idMunicipioAnterior) {
		this.idMunicipioAnterior = idMunicipioAnterior;
	}

	@Column(name = "municipio", nullable = false, length = 60)
	public String getMunicipio() {
		return this.municipio;
	}

	public void setMunicipio(String municipio) {
		this.municipio = municipio;
	}

	@Column(name = "id_estado", nullable = false)
	public int getIdEstado() {
		return this.idEstado;
	}

	public void setIdEstado(int idEstado) {
		this.idEstado = idEstado;
	}

	@Column(name = "id_municipio_por_estado", nullable = false)
	public int getIdMunicipioPorEstado() {
		return this.idMunicipioPorEstado;
	}

	public void setIdMunicipioPorEstado(int idMunicipioPorEstado) {
		this.idMunicipioPorEstado = idMunicipioPorEstado;
	}
}
