package mx.gob.cdmx.adip.beca.model;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.Table;

/**
 * CatPeriodoEscolar generated by Antonio Alcantar Valencia
 */
@Entity
@Table(name = "cat_periodo_escolar", schema = "mibecaparaempezar")
@NamedQueries({
	@NamedQuery(name="CatPeriodoEscolar.findAll"
			, query="SELECT NEW mx.gob.cdmx.adip.beca.commons.dto.CatPeriodoEscolarDTO "
					+ "( "
					+ "c.idPeriodoEscolar, "
					+ "c.descripcion, "
					+ "c.estatus "
					+ ") "
					+ "FROM CatPeriodoEscolar c "
					+ "where c.estatus = true "
					+ "	ORDER BY c.idPeriodoEscolar ASC ")
})
public class CatPeriodoEscolar implements java.io.Serializable {
		
	private static final long serialVersionUID = -8493803739019289554L;
	private Integer idPeriodoEscolar;
	private String descripcion;
	private Boolean estatus;

	public CatPeriodoEscolar() {
	}

	public CatPeriodoEscolar(Integer idPeriodoEscolar, String descripcion, Boolean estatus) {
		this.idPeriodoEscolar = idPeriodoEscolar;
		this.descripcion = descripcion;
		this.estatus = estatus;
	}

	@Id
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	@Column(name = "id_periodo_escolar", unique = true, nullable = false)
	public Integer getIdPeriodoEscolar() {
		return this.idPeriodoEscolar;
	}

	public void setIdPeriodoEscolar(Integer idPeriodoEscolar) {
		this.idPeriodoEscolar = idPeriodoEscolar;
	}

	@Column(name = "descripcion", nullable = false, length = 50)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Column(name = "estatus")
	public Boolean getEstatus() {
		return this.estatus;
	}

	public void setEstatus(Boolean estatus) {
		this.estatus = estatus;
	}


}
