package mx.gob.cdmx.adip.beca.model;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.Table;

/**
 * CatParentesco generated by hbm2java
 */
@Entity
@Table(name = "cat_parentesco", schema = "mibecaparaempezar")
@NamedQueries({
	@NamedQuery(name = "CatParentesco.findByEstatusActive" 
	, query = "SELECT NEW mx.gob.cdmx.adip.beca.commons.dto.CatParentescoDTO("
			+ "ctd.idParentesco,"
			+ "ctd.descripcion,"
			+ "ctd.estatus"
			+ ")"
			+ "	FROM CatParentesco ctd"
			+ "	WHERE ctd.estatus = TRUE")
})

public class CatParentesco implements java.io.Serializable {
	
	private static final long serialVersionUID = 3971814708631293658L;
	private int idParentesco;
	private String descripcion;
	private Boolean estatus;

	public CatParentesco() {
	}

	public CatParentesco(int idParentesco, String descripcion) {
		this.idParentesco = idParentesco;
		this.descripcion = descripcion;
	}

	public CatParentesco(int idParentesco, String descripcion, Boolean estatus) {
		this.idParentesco = idParentesco;
		this.descripcion = descripcion;
		this.estatus = estatus;
	}

	@Id
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	@Column(name = "id_parentesco", unique = true, nullable = false)
	public int getIdParentesco() {
		return this.idParentesco;
	}

	public void setIdParentesco(int idParentesco) {
		this.idParentesco = idParentesco;
	}

	@Column(name = "descripcion", nullable = false, length = 50)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Column(name = "estatus")
	public Boolean getEstatus() {
		return this.estatus;
	}

	public void setEstatus(Boolean estatus) {
		this.estatus = estatus;
	}
}
