package mx.gob.cdmx.adip.beca.model;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * CatTipoIne generated by hbm2java
 */
@Entity
@Table(name = "cat_tipo_ine", schema = "mibecaparaempezar")
public class CatTipoIne implements java.io.Serializable {
	
	private static final long serialVersionUID = -7698989406722445137L;
	private int idTipoIne;
	private String descripcion;
	private Boolean estatus;

	public CatTipoIne() {
	}

	public CatTipoIne(int idTipoIne) {
		this.idTipoIne = idTipoIne;
	}

	public CatTipoIne(int idTipoIne, String descripcion, Boolean estatus) {
		this.idTipoIne = idTipoIne;
		this.descripcion = descripcion;
		this.estatus = estatus;
	}

	@Id
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	@Column(name = "id_tipo_ine", unique = true, nullable = false)
	public int getIdTipoIne() {
		return this.idTipoIne;
	}

	public void setIdTipoIne(int idTipoIne) {
		this.idTipoIne = idTipoIne;
	}

	@Column(name = "descripcion", length = 20)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Column(name = "estatus")
	public Boolean getEstatus() {
		return this.estatus;
	}

	public void setEstatus(Boolean estatus) {
		this.estatus = estatus;
	}

}
