package mx.gob.cdmx.adip.beca.model;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * CatTipoDispersion generated by Antonio Alcantar Valencia
 */
@Entity
@Table(name = "cat_tipo_dispersion", schema = "mibecaparaempezar")
public class CatTipoDispersion implements java.io.Serializable {
		
	private static final long serialVersionUID = -8493803739019289554L;
	private Integer idTipoDispersion;
	private String descripcion;
	private Boolean estatus;

	public CatTipoDispersion() {
	}

	public CatTipoDispersion(Integer idTipoDispersion, String descripcion, Boolean estatus) {
		this.idTipoDispersion = idTipoDispersion;
		this.descripcion = descripcion;
		this.estatus = estatus;
	}

	@Id
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	@Column(name = "id_tipo_dispersion", unique = true, nullable = false)
	public Integer getIdTipoDispersion() {
		return this.idTipoDispersion;
	}

	public void setIdTipoDispersion(Integer idTipoDispersion) {
		this.idTipoDispersion = idTipoDispersion;
	}

	@Column(name = "descripcion", nullable = false, length = 50)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Column(name = "estatus")
	public Boolean getEstatus() {
		return this.estatus;
	}

	public void setEstatus(Boolean estatus) {
		this.estatus = estatus;
	}


}
