package mx.gob.cdmx.adip.beca.model;

import java.io.Serializable;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.Table;

/**
 * CatTipoDomicilio generated by hbm2java
 */
@Entity
@Table(name = "cat_tipo_domicilio", schema = "mibecaparaempezar")
@NamedQueries({
	@NamedQuery(name = "CatTipoDomicilio.findByEstatusActive" , query = "SELECT NEW mx.gob.cdmx.adip.beca.commons.dto.CatTipoDomicilioDTO("
			+ "ctd.idTipoDomicilio,"
			+ "ctd.descripcion,"
			+ "ctd.estatus"
			+ ")"
			+ "	FROM CatTipoDomicilio ctd"
			+ "	WHERE ctd.estatus = TRUE")
})
public class CatTipoDomicilio implements Serializable {
	
	private static final long serialVersionUID = 5301070129028325847L;
	private int idTipoDomicilio;
	private String descripcion;
	private Boolean estatus;

	public CatTipoDomicilio() {
	}

	public CatTipoDomicilio(int idTipoDomicilio) {
		this.idTipoDomicilio = idTipoDomicilio;
	}

	public CatTipoDomicilio(int idTipoDomicilio, String descripcion, Boolean estatus) {
		this.idTipoDomicilio = idTipoDomicilio;
		this.descripcion = descripcion;
		this.estatus = estatus;
	}

	@Id
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	@Column(name = "id_tipo_domicilio", unique = true, nullable = false)
	public int getIdTipoDomicilio() {
		return this.idTipoDomicilio;
	}

	public void setIdTipoDomicilio(int idTipoDomicilio) {
		this.idTipoDomicilio = idTipoDomicilio;
	}

	@Column(name = "descripcion")
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Column(name = "estatus")
	public Boolean getEstatus() {
		return this.estatus;
	}

	public void setEstatus(Boolean estatus) {
		this.estatus = estatus;
	}
}
