package mx.gob.cdmx.adip.beca.model;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.Table;

/**
 * CatTipoDispersion generated by Antonio Alcantar Valencia
 */
@Entity
@Table(name = "cat_tipo_dispersion", schema = "mibecaparaempezar")
@NamedQueries({
	@NamedQuery(name="CatTipoDispersion.findAll"
			, query="SELECT NEW mx.gob.cdmx.adip.beca.commons.dto.CatTipoDispersionDTO "
					+ "( "
					+ "c.idTipoDispersion, "
					+ "c.descripcion, "
					+ "c.estatus "
					+ ") "
					+ "FROM CatTipoDispersion c "
					+ "where c.estatus = true ")
})
public class CatTipoDispersion implements java.io.Serializable {
		
	private static final long serialVersionUID = -8493803739019289554L;
	private Long idTipoDispersion;
	private String descripcion;
	private Boolean estatus;

	public CatTipoDispersion() {
	}

	public CatTipoDispersion(Long idTipoDispersion, String descripcion, Boolean estatus) {
		this.idTipoDispersion = idTipoDispersion;
		this.descripcion = descripcion;
		this.estatus = estatus;
	}

	@Id
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	@Column(name = "id_tipo_dispersion", unique = true, nullable = false)
	public Long getIdTipoDispersion() {
		return this.idTipoDispersion;
	}

	public void setIdTipoDispersion(Long idTipoDispersion) {
		this.idTipoDispersion = idTipoDispersion;
	}

	@Column(name = "descripcion", nullable = false, length = 50)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Column(name = "estatus")
	public Boolean getEstatus() {
		return this.estatus;
	}

	public void setEstatus(Boolean estatus) {
		this.estatus = estatus;
	}


}
