package mx.gob.cdmx.adip.beca.model;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Dispersion generated by Antonio Alcantar Valencia
 */
@Entity
@Table(name = "dispersion", schema = "mibecaparaempezar")
@NamedQueries({
	@NamedQuery(name="Dispersion.findAll"
			, query="SELECT NEW mx.gob.cdmx.adip.beca.commons.dto.DispersionDTO "
					+ "( "
					+ "d.idDispersion, "
					+ "cce.idCicloEscolar, "
					+ "cce.descripcion, "
					+ "cpe.idPeriodoEscolar, "
					+ "cpe.descripcion, "
					+ "ctd.idTipoDispersion, "
					+ "ctd.descripcion, "
					+ "d.numBeneficiarios, "
					+ "d.fechaEjecucion, "
					+ "d.idUsuarioEjecucion, "
					+ "d.fechaConclusion, "
					+ "ced.idEstatusDispersion, "
					+ "ced.descripcion, "
					+ "d.aplicaDispersionPorcentaje, "
					+ "d.aplicaDispersionNumero, "
					+ "d.noAplicaDispersionPorcentaje, "
					+ "d.noAplicaDispersionNumero, "
					+ "d.fechaDescarga "
					+ ") "
					+ "FROM Dispersion d "
					+ "JOIN d.catCicloEscolar cce "
					+ "JOIN d.catPeriodoEscolar cpe "
					+ "JOIN d.catTipoDispersion ctd "
					+ "JOIN d.catEstatusDispersion ced"),
	@NamedQuery(name="Dispersion.findByCicloPeriodoAndTipoDispersion"
	, query="SELECT NEW mx.gob.cdmx.adip.beca.commons.dto.DispersionDTO "
			+ "( "
			+ "d.idDispersion, "
			+ "cce.idCicloEscolar, "
			+ "cce.descripcion, "
			+ "cpe.idPeriodoEscolar, "
			+ "cpe.descripcion, "
			+ "ctd.idTipoDispersion, "
			+ "ctd.descripcion, "
			+ "d.numBeneficiarios, "
			+ "d.fechaEjecucion, "
			+ "d.idUsuarioEjecucion, "
			+ "d.fechaConclusion, "
			+ "ced.idEstatusDispersion, "
			+ "ced.descripcion, "
			+ "d.aplicaDispersionPorcentaje, "
			+ "d.aplicaDispersionNumero, "
			+ "d.noAplicaDispersionPorcentaje, "
			+ "d.noAplicaDispersionNumero, "
			+ "d.fechaDescarga "
			+ ") "
			+ "FROM Dispersion d "
			+ "JOIN d.catCicloEscolar cce "
			+ "JOIN d.catPeriodoEscolar cpe "
			+ "JOIN d.catTipoDispersion ctd "
			+ "JOIN d.catEstatusDispersion ced "
			+ "WHERE cce.idCicloEscolar = :idCicloEscolar "
			+ "AND cpe.idPeriodoEscolar = :idPeriodoEscolar "
			+ "AND ctd.idTipoDispersion = :idTipoDispersion")
})
public class Dispersion implements java.io.Serializable {
	
	private static final long serialVersionUID = 1938283627957991307L;
	private Long idDispersion;
	private CatCicloEscolar catCicloEscolar;
	private CatPeriodoEscolar catPeriodoEscolar;
	private CatTipoDispersion catTipoDispersion;
	private Long numBeneficiarios;
	private Date fechaEjecucion;
	private Long idUsuarioEjecucion;
	private Date fechaConclusion;
	private CatEstatusDispersion catEstatusDispersion;
	private Double aplicaDispersionPorcentaje;
	private Long aplicaDispersionNumero;
	private Double noAplicaDispersionPorcentaje;
	private Long noAplicaDispersionNumero;
	private Date fechaDescarga;

	public Dispersion() {
	}
	
	public Dispersion(Long idDispersion, CatCicloEscolar catCicloEscolar, CatPeriodoEscolar catPeriodoEscolar,
			CatTipoDispersion catTipoDispersion, Long numBeneficiarios, Date fechaEjecucion, Long idUsuarioEjecucion,
			Date fechaConclusion, CatEstatusDispersion catEstatusDispersion, Double aplicaDispersionPorcentaje,
			Long aplicaDispersionNumero, Double noAplicaDispersionPorcentaje, Long noAplicaDispersionNumero,
			Date fechaDescarga) {
		this.idDispersion = idDispersion;
		this.catCicloEscolar = catCicloEscolar;
		this.catPeriodoEscolar = catPeriodoEscolar;
		this.catTipoDispersion = catTipoDispersion;
		this.numBeneficiarios = numBeneficiarios;
		this.fechaEjecucion = fechaEjecucion;
		this.idUsuarioEjecucion = idUsuarioEjecucion;
		this.fechaConclusion = fechaConclusion;
		this.catEstatusDispersion = catEstatusDispersion;
		this.aplicaDispersionPorcentaje = aplicaDispersionPorcentaje;
		this.aplicaDispersionNumero = aplicaDispersionNumero;
		this.noAplicaDispersionPorcentaje = noAplicaDispersionPorcentaje;
		this.noAplicaDispersionNumero = noAplicaDispersionNumero;
		this.fechaDescarga = fechaDescarga;
	}
	
	@Id
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	@Column(name = "id_dispersion", unique = true, nullable = false)
	public Long getIdDispersion() {
		return this.idDispersion;
	}

	public void setIdDispersion(Long idDispersion) {
		this.idDispersion = idDispersion;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_ciclo_escolar", nullable = false)
	public CatCicloEscolar getCatCicloEscolar() {
		return this.catCicloEscolar;
	}

	public void setCatCicloEscolar(CatCicloEscolar catCicloEscolar) {
		this.catCicloEscolar = catCicloEscolar;
	}
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_periodo_escolar", nullable = false)
	public CatPeriodoEscolar getCatPeriodoEscolar() {
		return this.catPeriodoEscolar;
	}

	public void setCatPeriodoEscolar(CatPeriodoEscolar catPeriodoEscolar) {
		this.catPeriodoEscolar = catPeriodoEscolar;
	}
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_tipo_dispersion", nullable = false)
	public CatTipoDispersion getCatTipoDispersion() {
		return this.catTipoDispersion;
	}

	public void setCatTipoDispersion(CatTipoDispersion catTipoDispersion) {
		this.catTipoDispersion = catTipoDispersion;
	}

	@Column(name = "num_beneficiarios", nullable = false)
	public Long getNumBeneficiarios() {
		return this.numBeneficiarios;
	}

	public void setNumBeneficiarios(Long numBeneficiarios) {
		this.numBeneficiarios = numBeneficiarios;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_ejecucion", nullable = false)
	public Date getFechaEjecucion() {
		return this.fechaEjecucion;
	}

	public void setFechaEjecucion(Date fechaEjecucion) {
		this.fechaEjecucion = fechaEjecucion;
	}

	@Column(name = "id_usuario_ejecucion", nullable = false)
	public Long getIdUsuarioEjecucion() {
		return this.idUsuarioEjecucion;
	}

	public void setIdUsuarioEjecucion(Long idUsuarioEjecucion) {
		this.idUsuarioEjecucion = idUsuarioEjecucion;
	}
	
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_conclusion", nullable = false)
	public Date getFechaConclusion() {
		return this.fechaConclusion;
	}

	public void setFechaConclusion(Date fechaConclusion) {
		this.fechaConclusion = fechaConclusion;
	}
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_estatus_dispersion", nullable = false)
	public CatEstatusDispersion getCatEstatusDispersion() {
		return this.catEstatusDispersion;
	}

	public void setCatEstatusDispersion(CatEstatusDispersion catEstatusDispersion) {
		this.catEstatusDispersion = catEstatusDispersion;
	}
	
	@Column(name = "aplica_dispersion_porcentaje", nullable = false)
	public Double getAplicaDispersionPorcentaje() {
		return this.aplicaDispersionPorcentaje;
	}

	public void setAplicaDispersionPorcentaje(Double aplicaDispersionPorcentaje) {
		this.aplicaDispersionPorcentaje = aplicaDispersionPorcentaje;
	}
	
	@Column(name = "aplica_dispersion_numero", nullable = false)
	public Long getAplicaDispersionNumero() {
		return this.aplicaDispersionNumero;
	}

	public void setAplicaDispersionNumero(Long aplicaDispersionNumero) {
		this.aplicaDispersionNumero = aplicaDispersionNumero;
	}
	
	@Column(name = "no_aplica_dispersion_porcentaje", nullable = false)
	public Double getNoAplicaDispersionPorcentaje() {
		return this.noAplicaDispersionPorcentaje;
	}

	public void setNoAplicaDispersionPorcentaje(Double noAplicaDispersionPorcentaje) {
		this.noAplicaDispersionPorcentaje = noAplicaDispersionPorcentaje;
	}
	
	@Column(name = "no_aplica_dispersion_numero", nullable = false)
	public Long getNoAplicaDispersionNumero() {
		return this.noAplicaDispersionNumero;
	}

	public void setNoAplicaDispersionNumero(Long noAplicaDispersionNumero) {
		this.noAplicaDispersionNumero = noAplicaDispersionNumero;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_descarga", nullable = false)
	public Date getFechaDescarga() {
		return this.fechaDescarga;
	}

	public void setFechaDescarga(Date fechaDescarga) {
		this.fechaDescarga = fechaDescarga;
	}

}
