package mx.gob.cdmx.adip.beca.model;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Solicitud generated by hbm2java
 */
@Entity
@Table(name = "solicitud", schema = "mibecaparaempezar")
@NamedQueries({
	@NamedQuery(name = "Solicitud.findAll", query = "SELECT s FROM Solicitud s")
	,
	@NamedQuery(name = "Solicitud.findById", query = "SELECT NEW mx.gob.cdmx.adip.beca.commons.dto.SolicitudDTO "
			+"( "
			+ "s.idSolicitud, "
			+ "s.folioSolicitud, "
			+ "t.idUsuarioLlaveCdmx, "
			+ "t.nombre, "
			+ "t.primerApellido, "
			+ "t.segundoApellido, "
			+ "t.curp, "
			+ "b.idBeneficiario, "
			+ "b.nombresBeneficiario, "
			+ "b.primerApellidoBeneficiario, "
			+ "b.segundoApellidoBeneficiario, "
			+ "b.nacionalidad, b.curpBeneficiario, "
			+ "te.idEstatus, te.descripcion, "
			+ "ceb.idEstatusBeneficiario, ceb.descripcion"
			+") "
			+"FROM CrcBeneficiarioSolicitud crc "
			+"JOIN crc.beneficiario b "
			+"JOIN crc.solicitud s "  
			+"JOIN s.tutor t "
			+"JOIN t.catEstatus te "
			+"JOIN s.catEstatusBeneficiario ceb "
			+"JOIN s.catMunicipios cm "
			+"where s.idSolicitud = :idSolicitud ")
})
public class Solicitud implements java.io.Serializable {
	
	private static final long serialVersionUID = 1938283627957991307L;
	private Long idSolicitud;
	private CatEstatusBeneficiario catEstatusBeneficiario;
	private CatParentesco catParentesco;
	private CatMunicipios catMunicipios;
	private Tutor tutor;
	private String folioSolicitud;
	private Date fechaSolicitud;
	private String respuestaAutoridadEducativa;
	private String cct;
	private String nombre;
	private String calle;
	private String colonia;
	private String alcaldia;
	private String codigopostal;
	private String turno;
	private CatNivelEducativo catNivelEducativo;
	private String gradoEscolar;
	private boolean envioExitoso;
	private Set<Encuesta> encuestas = new HashSet<Encuesta>(0);

	public Solicitud() {
	}

//	public Solicitud(Long idSolicitud, CatEstatus catEstatus, CatParentesco catParentesco, Tutor tutor,
//			Usuariofidegar usuariofidegar, String folioSolicitud, Date fechaSolicitud,
//			String respuestaAutoridadEducativa, boolean envioExitoso) {
//		this.idSolicitud = idSolicitud;
//		//this.catEstatus = catEstatus;
//		this.catParentesco = catParentesco;
//		this.tutor = tutor;
//		//this.usuariofidegar = usuariofidegar;
//		this.folioSolicitud = folioSolicitud;
//		this.fechaSolicitud = fechaSolicitud;
//		this.respuestaAutoridadEducativa = respuestaAutoridadEducativa;
//		this.envioExitoso = envioExitoso;
//	}

//	public Solicitud(Long idSolicitud, CatEstatus catEstatus, CatParentesco catParentesco,
//			MotivosRechazoBeneficiario motivosRechazoBeneficiario, Tutor tutor, Usuariofidegar usuariofidegar,
//			String folioSolicitud, Date fechaSolicitud, String respuestaAutoridadEducativa, Integer idUsuarioFidegar,
//			String cct, String nombre, String calle, String colonia, String alcaldia, String codigopostal, String turno,
//			String nivelEducativo, String gradoEscolar, String estatus, boolean envioExitoso,
//			Set<ApoyosPendientesEntregar> apoyosPendientesEntregars, Set<Encuesta> encuestas,
//			Set<BitacoraCambiosTutor> bitacoraCambiosTutors, Set<CrcBeneficiarioSolicitud> crcBeneficiarioSolicituds,
//			Set<DetRevisionSolicitud> detRevisionSolicituds, Set<Tarjeta> tarjetas) {
//		this.idSolicitud = idSolicitud;
//		//this.catEstatus = catEstatus;
//		this.catParentesco = catParentesco;
//		//this.motivosRechazoBeneficiario = motivosRechazoBeneficiario;
//		this.tutor = tutor;
//		//this.usuariofidegar = usuariofidegar;
//		this.folioSolicitud = folioSolicitud;
//		this.fechaSolicitud = fechaSolicitud;
//		this.respuestaAutoridadEducativa = respuestaAutoridadEducativa;
//		//this.idUsuarioFidegar = idUsuarioFidegar;
//		this.cct = cct;
//		this.nombre = nombre;
//		this.calle = calle;
//		this.colonia = colonia;
//		this.alcaldia = alcaldia;
//		this.codigopostal = codigopostal;
//		this.turno = turno;
//		this.nivelEducativo = nivelEducativo;
//		this.gradoEscolar = gradoEscolar;
//		this.estatus = estatus;
//		this.envioExitoso = envioExitoso;
//		this.apoyosPendientesEntregars = apoyosPendientesEntregars;
//		this.encuestas = encuestas;
//		this.bitacoraCambiosTutors = bitacoraCambiosTutors;
//		this.crcBeneficiarioSolicituds = crcBeneficiarioSolicituds;
//		this.detRevisionSolicituds = detRevisionSolicituds;
//		this.tarjetas = tarjetas;
//	}

	
	@Id
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	@Column(name = "id_solicitud", unique = true, nullable = false)
	public Long getIdSolicitud() {
		return this.idSolicitud;
	}

	public void setIdSolicitud(Long idSolicitud) {
		this.idSolicitud = idSolicitud;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_estatus_beneficiario", nullable = false)
	public CatEstatusBeneficiario getCatEstatusBeneficiario() {
		return this.catEstatusBeneficiario;
	}

	public void setCatEstatusBeneficiario(CatEstatusBeneficiario catEstatusBeneficiario) {
		this.catEstatusBeneficiario = catEstatusBeneficiario;
	}
	
	
//	@ManyToOne(fetch = FetchType.LAZY)
//	@JoinColumn(name = "id_estatus", nullable = false)
//	public CatEstatus getCatEstatus() {
//		return this.catEstatus;
//	}
//
//	public void setCatEstatus(CatEstatus catEstatus) {
//		this.catEstatus = catEstatus;
//	}
	

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_parentesco", nullable = false)
	public CatParentesco getCatParentesco() {
		return this.catParentesco;
	}

	public void setCatParentesco(CatParentesco catParentesco) {
		this.catParentesco = catParentesco;
	}


	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_usuario_llave_cdmx", nullable = false)
	public Tutor getTutor() {
		return this.tutor;
	}

	public void setTutor(Tutor tutor) {
		this.tutor = tutor;
	}

	@Column(name = "folio_solicitud", nullable = false, length = 15)
	public String getFolioSolicitud() {
		return this.folioSolicitud;
	}

	public void setFolioSolicitud(String folioSolicitud) {
		this.folioSolicitud = folioSolicitud;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_solicitud", nullable = false, length = 29)
	public Date getFechaSolicitud() {
		return this.fechaSolicitud;
	}

	public void setFechaSolicitud(Date fechaSolicitud) {
		this.fechaSolicitud = fechaSolicitud;
	}

	@Column(name = "respuesta_autoridad_educativa", nullable = false)
	public String getRespuestaAutoridadEducativa() {
		return this.respuestaAutoridadEducativa;
	}

	public void setRespuestaAutoridadEducativa(String respuestaAutoridadEducativa) {
		this.respuestaAutoridadEducativa = respuestaAutoridadEducativa;
	}

	@Column(name = "cct", length = 15)
	public String getCct() {
		return this.cct;
	}

	public void setCct(String cct) {
		this.cct = cct;
	}

	@Column(name = "nombre", length = 200)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "calle", length = 200)
	public String getCalle() {
		return this.calle;
	}

	public void setCalle(String calle) {
		this.calle = calle;
	}

	@Column(name = "colonia", length = 100)
	public String getColonia() {
		return this.colonia;
	}

	public void setColonia(String colonia) {
		this.colonia = colonia;
	}

	@Column(name = "alcaldia", length = 50)
	public String getAlcaldia() {
		return this.alcaldia;
	}

	public void setAlcaldia(String alcaldia) {
		this.alcaldia = alcaldia;
	}

	@Column(name = "codigopostal", length = 5)
	public String getCodigopostal() {
		return this.codigopostal;
	}

	public void setCodigopostal(String codigopostal) {
		this.codigopostal = codigopostal;
	}

	@Column(name = "turno", length = 100)
	public String getTurno() {
		return this.turno;
	}

	public void setTurno(String turno) {
		this.turno = turno;
	}
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_nivel_educativo")
	public CatNivelEducativo getCatNivelEducativo() {
		return catNivelEducativo;
	}

	public void setCatNivelEducativo(CatNivelEducativo catNivelEducativo) {
		this.catNivelEducativo = catNivelEducativo;
	}

	@Column(name = "grado_escolar", length = 50)
	public String getGradoEscolar() {
		return this.gradoEscolar;
	}	

	public void setGradoEscolar(String gradoEscolar) {
		this.gradoEscolar = gradoEscolar;
	}

	@Column(name = "envio_exitoso", nullable = false)
	public boolean isEnvioExitoso() {
		return this.envioExitoso;
	}

	public void setEnvioExitoso(boolean envioExitoso) {
		this.envioExitoso = envioExitoso;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "solicitud")
	public Set<Encuesta> getEncuestas() {
		return this.encuestas;
	}

	public void setEncuestas(Set<Encuesta> encuestas) {
		this.encuestas = encuestas;
	}
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_alcaldia", nullable = false)
	public CatMunicipios getCatMunicipios() {
		return this.catMunicipios;
	}

	public void setCatMunicipios(CatMunicipios catMunicipios) {
		this.catMunicipios = catMunicipios;
	}

}
