package mx.gob.cdmx.adip.beca.model;

import java.io.Serializable;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.Table;

/**
 * Tutor generated by hbm2java
 */
@Entity
@Table(name = "tutor", schema = "mibecaparaempezar")
@NamedQueries({
	@NamedQuery(name = "Tutor.findByIdLlave", query = "SELECT NEW mx.gob.cdmx.adip.beca.commons.dto.TutorDTO " 
			+ "( "
			+ " t.idUsuarioLlaveCdmx,"
			+ " t.nombre,"
			+ " t.primerApellido,"
			+ " t.segundoApellido,"
			+ " t.curp,"
			+ " t.telefono,"
			+ " t.correo,"
			+ " cio.idIdentificacion,"
			+ " cio.descripcion,"
			+ " cio.idCatLlave,"
			+ " t.archivoIdentificacion,"
			+ " t.ocr,"
			+ " t.calle,"
			+ " t.numInt,"
			+ " t.numExt,"
			+ " t.codigoPostal,"
			+ " ccd.idComprobanteDomicilio,"
			+ " ccd.descripcion,"
			+ " t.archivoComprobanteDomicilio,"
			+ " cm.idMunicipio,"
			+ " ca.idAsentamiento,"
			+ " t.cic,"
			+ " t.claveElector,"
			+ " t.numeroEmision,"
			+ " t.nacionalidad,"
			+ " t.informacionGralCorrecto,"
			+ " t.domicilioCorrecto,"
			+ " ce.idEstatus,"
			+ " ce.descripcion,"
			+ " t.informacionGeneralObservaciones,"
			+ " t.domicilioObservaciones,"
			+ " cti.idTipoIne,"
			+ " t.esExtranjero,"
			+ " t.esMayorTresBeneficiarios,"
			+ " t.esCasaHogar,"
			+ " t.nombreCasaHogar,"
			+ " t.motivoMayorTresBeneficiarios,"
			+ " t.documentoLlave,"
			+ " t.idDocumentoLlave"
			+ " )"
			+ " FROM Tutor t"
			+ "	LEFT JOIN t.catIdentificacionOficial cio"
			+ "	LEFT JOIN t.catMunicipios cm"
			+ "	LEFT JOIN t.catAsentamientos ca"
			+ "	LEFT JOIN t.catEstatus ce"
			+ "	LEFT JOIN t.catTipoIne cti"
			+ "	LEFT JOIN t.catComprobanteDomicilio ccd"
			+ " WHERE t.idUsuarioLlaveCdmx = :idUsuarioLlave" )
	,
	@NamedQuery(name = "Tutor.findByCurp", query = "SELECT NEW mx.gob.cdmx.adip.beca.commons.dto.TutorDTO("
			+ " t.idUsuarioLlaveCdmx,"
			+ " t.nombre,"
			+ " t.primerApellido,"
			+ " t.segundoApellido,"
			+ " t.curp,"
			+ " t.telefono,"
			+ " t.correo,"
			+ " t.esExtranjero"
			+ ")"
			+ " FROM Tutor t"
			+ "	JOIN t.catEstatus ce"
			+ " WHERE t.curp = :curp"
			+ " and ce.idEstatus <> 8 "
			)
	, @NamedQuery(name = "Tutor.findByNombreAPaterno"
	, query = "SELECT NEW mx.gob.cdmx.adip.beca.commons.dto.TutorDTO("
			+ " t.idUsuarioLlaveCdmx,"
			+ " t.nombre,"
			+ " t.primerApellido,"
			+ " t.segundoApellido,"
			+ " t.curp,"
			+ " t.telefono,"
			+ " t.correo,"
			+ " t.esExtranjero"
			+ ")"
			+ " FROM Tutor t"
			+ "	JOIN t.catEstatus ce"
			+ " WHERE t.nombre LIKE :nombrecompleto"
			+ " and t.primerApellido LIKE :apellidoPaterno"
			+ " and ce.idEstatus <> 8 "
			)
	, @NamedQuery(name = "Tutor.findByNombreAMaterno"
	, query = "SELECT NEW mx.gob.cdmx.adip.beca.commons.dto.TutorDTO("
			+ " t.idUsuarioLlaveCdmx,"
			+ " t.nombre,"
			+ " t.primerApellido,"
			+ " t.segundoApellido,"
			+ " t.curp,"
			+ " t.telefono,"
			+ " t.correo,"
			+ " t.esExtranjero"
			+ ")"
			+ " FROM Tutor t"
			+ "	JOIN t.catEstatus ce"
			+ " WHERE t.nombre LIKE :nombrecompleto"
			+ " and t.primerApellido LIKE :apellidoPaterno"
			+ " and t.segundoApellido LIKE :apellidoMaterno"
			+ " and ce.idEstatus <> 8 "			
			)
	,
	@NamedQuery(name = "Tutor.updateEstatusCorreccion", query = "UPDATE Tutor t "
			+ "	SET"
			+ "	t.informacionGralCorrecto = :infoGralCorrecto,"
			+ "	t.informacionGeneralObservaciones = :infoGralObservaciones,"
			+ "	t.domicilioCorrecto = :domicilioCorrecto,"
			+ "	t.domicilioObservaciones = :domicilioObservaciones,"
			+ "	t.catEstatus.idEstatus = :idEstatus"
			+ "	WHERE t.idUsuarioLlaveCdmx = :idUsuarioLlaveCdmx")
	,
	@NamedQuery(name = "Tutor.updateMasBeneficiarios", query = "UPDATE Tutor t "
			+ "	SET"
			+ "	t.esMayorTresBeneficiarios = :esMayorTresBeneficiarios,"
			+ "	t.esCasaHogar = :esCasaHogar, "
			+ "	t.nombreCasaHogar = :nombreCasaHogar, "
			+ "	t.motivoMayorTresBeneficiarios = :motivoMayorTresBeneficiarios "
			+ "	WHERE t.idUsuarioLlaveCdmx = :idUsuarioLlaveCdmx")
	,
	@NamedQuery(name = "Tutor.consultaHomonimias", query = "SELECT t.curp FROM Tutor t "
			+ "	WHERE t.curp like :curp"
			+ "	AND t.esExtranjero = TRUE")
	
})
public class Tutor implements Serializable {
	
	private static final long serialVersionUID = 6323187684449216779L;
	private Long idUsuarioLlaveCdmx;
	private CatAsentamientos catAsentamientos;
	private CatEstatus catEstatus;
	private CatIdentificacionOficial catIdentificacionOficial;
	private CatMunicipios catMunicipios;
	private CatTipoIne catTipoIne;
	private String nombre;
	private String primerApellido;
	private String segundoApellido;
	private String curp;
	private String telefono;
	private String correo;
	private String archivoIdentificacion;
	private String ocr;
	private String calle;
	private String numInt;
	private String numExt;
	private String codigoPostal;
	private CatComprobanteDomicilio catComprobanteDomicilio;
	private String archivoComprobanteDomicilio;
	private String cic;
	private String claveElector;
	private String numeroEmision;
	private String nacionalidad;
	private Boolean informacionGralCorrecto;
	private Boolean domicilioCorrecto;
	private String informacionGeneralObservaciones;
	private String domicilioObservaciones;
	private boolean esExtranjero;
	private boolean esMayorTresBeneficiarios;
	private boolean esCasaHogar;
	private String nombreCasaHogar;
	private String motivoMayorTresBeneficiarios;
	private boolean documentoLlave;
	private Integer idDocumentoLlave;
	private String lada;

	public Tutor() {
	}

	public Tutor(Long idUsuarioLlaveCdmx, CatAsentamientos catAsentamientos, CatEstatus catEstatus,
			CatIdentificacionOficial catIdentificacionOficial, CatMunicipios catMunicipios, String nombre,
			String primerApellido, String telefono, String correo, String archivoIdentificacion, String calle,
			String numInt, String codigoPostal, CatComprobanteDomicilio catComprobanteDomicilio, String archivoComprobanteDomicilio,
			String nacionalidad, boolean esExtranjero, boolean esMayorTresBeneficiarios, boolean esCasaHogar , String nombreCasaHogar, String motivoMayorTresBeneficiarios  ) {
		this.idUsuarioLlaveCdmx = idUsuarioLlaveCdmx;
		this.catAsentamientos = catAsentamientos;
		this.catEstatus = catEstatus;
		this.catIdentificacionOficial = catIdentificacionOficial;
		this.catMunicipios = catMunicipios;
		this.nombre = nombre;
		this.primerApellido = primerApellido;
		this.telefono = telefono;
		this.correo = correo;
		this.archivoIdentificacion = archivoIdentificacion;
		this.calle = calle;
		this.numInt = numInt;
		this.codigoPostal = codigoPostal;
		this.catComprobanteDomicilio = catComprobanteDomicilio;
		this.archivoComprobanteDomicilio = archivoComprobanteDomicilio;
		this.nacionalidad = nacionalidad;
		this.esExtranjero = esExtranjero;
		this.esMayorTresBeneficiarios = esMayorTresBeneficiarios;
		this.esCasaHogar = esCasaHogar;
		this.motivoMayorTresBeneficiarios = motivoMayorTresBeneficiarios;
	}

	public Tutor(Long idUsuarioLlaveCdmx, CatAsentamientos catAsentamientos, CatEstatus catEstatus,
			CatIdentificacionOficial catIdentificacionOficial, CatMunicipios catMunicipios, CatTipoIne catTipoIne,
			String nombre, String primerApellido, String segundoApellido, String curp, String telefono, String correo,
			String archivoIdentificacion, String ocr, String calle, String numInt, String numExt, String codigoPostal,
			CatComprobanteDomicilio catComprobanteDomicilio, String archivoComprobanteDomicilio, String cic, String claveElector,
			String numeroEmision, String nacionalidad, Boolean informacionGralCorrecto, Boolean domicilioCorrecto,
			String informacionGeneralObservaciones, String domicilioObservaciones, boolean esExtranjero) {
		this.idUsuarioLlaveCdmx = idUsuarioLlaveCdmx;
		this.catAsentamientos = catAsentamientos;
		this.catEstatus = catEstatus;
		this.catIdentificacionOficial = catIdentificacionOficial;
		this.catMunicipios = catMunicipios;
		this.catTipoIne = catTipoIne;
		this.nombre = nombre;
		this.primerApellido = primerApellido;
		this.segundoApellido = segundoApellido;
		this.curp = curp;
		this.telefono = telefono;
		this.correo = correo;
		this.archivoIdentificacion = archivoIdentificacion;
		this.ocr = ocr;
		this.calle = calle;
		this.numInt = numInt;
		this.numExt = numExt;
		this.codigoPostal = codigoPostal;
		this.catComprobanteDomicilio = catComprobanteDomicilio;
		this.archivoComprobanteDomicilio = archivoComprobanteDomicilio;
		this.cic = cic;
		this.claveElector = claveElector;
		this.numeroEmision = numeroEmision;
		this.nacionalidad = nacionalidad;
		this.informacionGralCorrecto = informacionGralCorrecto;
		this.domicilioCorrecto = domicilioCorrecto;
		this.informacionGeneralObservaciones = informacionGeneralObservaciones;
		this.domicilioObservaciones = domicilioObservaciones;
		this.esExtranjero = esExtranjero;
	}

	@Id
	@Column(name = "id_usuario_llave_cdmx", unique = true, nullable = false)
	public Long getIdUsuarioLlaveCdmx() {
		return this.idUsuarioLlaveCdmx;
	}

	public void setIdUsuarioLlaveCdmx(Long idUsuarioLlaveCdmx) {
		this.idUsuarioLlaveCdmx = idUsuarioLlaveCdmx;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_asentamiento", nullable = false)
	public CatAsentamientos getCatAsentamientos() {
		return this.catAsentamientos;
	}

	public void setCatAsentamientos(CatAsentamientos catAsentamientos) {
		this.catAsentamientos = catAsentamientos;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_estatus", nullable = false)
	public CatEstatus getCatEstatus() {
		return this.catEstatus;
	}

	public void setCatEstatus(CatEstatus catEstatus) {
		this.catEstatus = catEstatus;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_identificacion", nullable = false)
	public CatIdentificacionOficial getCatIdentificacionOficial() {
		return this.catIdentificacionOficial;
	}

	public void setCatIdentificacionOficial(CatIdentificacionOficial catIdentificacionOficial) {
		this.catIdentificacionOficial = catIdentificacionOficial;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_municipio", nullable = false)
	public CatMunicipios getCatMunicipios() {
		return this.catMunicipios;
	}

	public void setCatMunicipios(CatMunicipios catMunicipios) {
		this.catMunicipios = catMunicipios;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_tipo_ine")
	public CatTipoIne getCatTipoIne() {
		return this.catTipoIne;
	}

	public void setCatTipoIne(CatTipoIne catTipoIne) {
		this.catTipoIne = catTipoIne;
	}

	@Column(name = "nombre", nullable = false, length = 60)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "primer_apellido", nullable = false, length = 60)
	public String getPrimerApellido() {
		return this.primerApellido;
	}

	public void setPrimerApellido(String primerApellido) {
		this.primerApellido = primerApellido;
	}

	@Column(name = "segundo_apellido", length = 60)
	public String getSegundoApellido() {
		return this.segundoApellido;
	}

	public void setSegundoApellido(String segundoApellido) {
		this.segundoApellido = segundoApellido;
	}

	@Column(name = "curp", length = 18)
	public String getCurp() {
		return this.curp;
	}

	public void setCurp(String curp) {
		this.curp = curp;
	}

	@Column(name = "telefono", nullable = false, length = 15)
	public String getTelefono() {
		return this.telefono;
	}

	public void setTelefono(String telefono) {
		this.telefono = telefono;
	}

	@Column(name = "correo", nullable = false, length = 60)
	public String getCorreo() {
		return this.correo;
	}

	public void setCorreo(String correo) {
		this.correo = correo;
	}

	@Column(name = "archivo_identificacion", nullable = false, length = 200)
	public String getArchivoIdentificacion() {
		return this.archivoIdentificacion;
	}

	public void setArchivoIdentificacion(String archivoIdentificacion) {
		this.archivoIdentificacion = archivoIdentificacion;
	}

	@Column(name = "ocr", length = 18)
	public String getOcr() {
		return this.ocr;
	}

	public void setOcr(String ocr) {
		this.ocr = ocr;
	}

	@Column(name = "calle", nullable = false, length = 200)
	public String getCalle() {
		return this.calle;
	}

	public void setCalle(String calle) {
		this.calle = calle;
	}

	@Column(name = "num_int", nullable = false, length = 200)
	public String getNumInt() {
		return this.numInt;
	}

	public void setNumInt(String numInt) {
		this.numInt = numInt;
	}

	@Column(name = "num_ext", length = 200)
	public String getNumExt() {
		return this.numExt;
	}

	public void setNumExt(String numExt) {
		this.numExt = numExt;
	}

	@Column(name = "codigo_postal", nullable = false, length = 200)
	public String getCodigoPostal() {
		return this.codigoPostal;
	}

	public void setCodigoPostal(String codigoPostal) {
		this.codigoPostal = codigoPostal;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_comprobante_domicilio", nullable = false)
	public CatComprobanteDomicilio getCatComprobanteDomicilio() {
		return catComprobanteDomicilio;
	}

	public void setCatComprobanteDomicilio(CatComprobanteDomicilio catComprobanteDomicilio) {
		this.catComprobanteDomicilio = catComprobanteDomicilio;
	}

	@Column(name = "archivo_comprobante_domicilio", nullable = false, length = 200)
	public String getArchivoComprobanteDomicilio() {
		return this.archivoComprobanteDomicilio;
	}

	public void setArchivoComprobanteDomicilio(String archivoComprobanteDomicilio) {
		this.archivoComprobanteDomicilio = archivoComprobanteDomicilio;
	}

	@Column(name = "cic", length = 15)
	public String getCic() {
		return this.cic;
	}

	public void setCic(String cic) {
		this.cic = cic;
	}

	@Column(name = "clave_elector", length = 18)
	public String getClaveElector() {
		return this.claveElector;
	}

	public void setClaveElector(String claveElector) {
		this.claveElector = claveElector;
	}

	@Column(name = "numero_emision", length = 2)
	public String getNumeroEmision() {
		return this.numeroEmision;
	}

	public void setNumeroEmision(String numeroEmision) {
		this.numeroEmision = numeroEmision;
	}

	@Column(name = "nacionalidad", nullable = false, length = 50)
	public String getNacionalidad() {
		return this.nacionalidad;
	}

	public void setNacionalidad(String nacionalidad) {
		this.nacionalidad = nacionalidad;
	}

	@Column(name = "informacion_gral_correcto")
	public Boolean getInformacionGralCorrecto() {
		return this.informacionGralCorrecto;
	}

	public void setInformacionGralCorrecto(Boolean informacionGralCorrecto) {
		this.informacionGralCorrecto = informacionGralCorrecto;
	}

	@Column(name = "domicilio_correcto")
	public Boolean getDomicilioCorrecto() {
		return this.domicilioCorrecto;
	}

	public void setDomicilioCorrecto(Boolean domicilioCorrecto) {
		this.domicilioCorrecto = domicilioCorrecto;
	}

	@Column(name = "informacion_general_observaciones")
	public String getInformacionGeneralObservaciones() {
		return this.informacionGeneralObservaciones;
	}

	public void setInformacionGeneralObservaciones(String informacionGeneralObservaciones) {
		this.informacionGeneralObservaciones = informacionGeneralObservaciones;
	}

	@Column(name = "domicilio_observaciones")
	public String getDomicilioObservaciones() {
		return this.domicilioObservaciones;
	}

	public void setDomicilioObservaciones(String domicilioObservaciones) {
		this.domicilioObservaciones = domicilioObservaciones;
	}

	@Column(name = "es_mayor_tres_beneficiarios")
	public boolean isEsMayorTresBeneficiarios() {
		return this.esMayorTresBeneficiarios;
	}

	public void setEsMayorTresBeneficiarios(boolean esMayorTresBeneficiarios) {
		this.esMayorTresBeneficiarios = esMayorTresBeneficiarios;
	}
	
	
	@Column(name = "es_casa_hogar")
	public boolean isEsCasaHogar() {
		return this.esCasaHogar;
	}

	public void setEsCasaHogar(boolean esCasaHogar) {
		this.esCasaHogar = esCasaHogar;
	}
	
	
	@Column(name = "es_extranjero", nullable = true)
	public boolean isEsExtranjero() {
		return this.esExtranjero;
	}

	public void setEsExtranjero(boolean esExtranjero) {
		this.esExtranjero = esExtranjero;
	}
	
	
	@Column(name = "nombre_casa_hogar")
	public String getNombreCasaHogar() {
		return this.nombreCasaHogar;
	}

	public void setNombreCasaHogar(String nombreCasaHogar) {
		this.nombreCasaHogar = nombreCasaHogar;
	}
	
	
	
	@Column(name = "motivo_mayor_tres_beneficiarios")
	public String getMotivoMayorTresBeneficiarios() {
		return this.motivoMayorTresBeneficiarios;
	}

	public void setMotivoMayorTresBeneficiarios(String motivoMayorTresBeneficiarios) {
		this.motivoMayorTresBeneficiarios = motivoMayorTresBeneficiarios;
	}

	@Column(name = "documento_llave")
	public boolean isDocumentoLlave() {
		return documentoLlave;
	}

	public void setDocumentoLlave(boolean documentoLlave) {
		this.documentoLlave = documentoLlave;
	}

	@Column(name = "id_documento_llave")
	public Integer getIdDocumentoLlave() {
		return idDocumentoLlave;
	}

	public void setIdDocumentoLlave(Integer idDocumentoLlave) {
		this.idDocumentoLlave = idDocumentoLlave;
	}
	
	@Column(name = "lada")
	public String getLada() {
		return lada;
	}

	public void setLada(String lada) {
		this.lada = lada;
	}

}
