
package mx.gob.cdmx.adip.beca.soap.client.aefcm;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "MciWSService", targetNamespace = "http://mci.ws.dds.aefcm.gob.mx/", wsdlLocation = "https://www6.aefcm.gob.mx:9024/mciws/services/mciService?wsdl")
public class MciWSService
    extends Service
{

    private final static URL MCIWSSERVICE_WSDL_LOCATION;
    private final static WebServiceException MCIWSSERVICE_EXCEPTION;
    private final static QName MCIWSSERVICE_QNAME = new QName("http://mci.ws.dds.aefcm.gob.mx/", "MciWSService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("https://www6.aefcm.gob.mx:9024/mciws/services/mciService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        MCIWSSERVICE_WSDL_LOCATION = url;
        MCIWSSERVICE_EXCEPTION = e;
    }

    public MciWSService() {
        super(__getWsdlLocation(), MCIWSSERVICE_QNAME);
    }

    public MciWSService(WebServiceFeature... features) {
        super(__getWsdlLocation(), MCIWSSERVICE_QNAME, features);
    }

    public MciWSService(URL wsdlLocation) {
        super(wsdlLocation, MCIWSSERVICE_QNAME);
    }

    public MciWSService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, MCIWSSERVICE_QNAME, features);
    }

    public MciWSService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public MciWSService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns MciWS
     */
    @WebEndpoint(name = "MciWSPort")
    public MciWS getMciWSPort() {
        return super.getPort(new QName("http://mci.ws.dds.aefcm.gob.mx/", "MciWSPort"), MciWS.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns MciWS
     */
    @WebEndpoint(name = "MciWSPort")
    public MciWS getMciWSPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://mci.ws.dds.aefcm.gob.mx/", "MciWSPort"), MciWS.class, features);
    }

    private static URL __getWsdlLocation() {
        if (MCIWSSERVICE_EXCEPTION!= null) {
            throw MCIWSSERVICE_EXCEPTION;
        }
        return MCIWSSERVICE_WSDL_LOCATION;
    }

}
