
package mx.gob.cdmx.adip.beca.soap.client.aefcm;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "MciWS", targetNamespace = "http://mci.ws.dds.aefcm.gob.mx/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface MciWS {


    /**
     * 
     * @param arg0
     * @return
     *     returns mx.gob.cdmx.adip.mibecaparaempezar.soap.client.aefcm.MciResponse
     */
    @WebMethod
    @WebResult(name = "response", targetNamespace = "")
    @RequestWrapper(localName = "queryByCurp", targetNamespace = "http://mci.ws.dds.aefcm.gob.mx/", className = "mx.gob.cdmx.adip.mibecaparaempezar.soap.client.aefcm.QueryByCurp")
    @ResponseWrapper(localName = "queryByCurpResponse", targetNamespace = "http://mci.ws.dds.aefcm.gob.mx/", className = "mx.gob.cdmx.adip.mibecaparaempezar.soap.client.aefcm.QueryByCurpResponse")
    public MciResponse queryByCurp(
        @WebParam(name = "arg0", targetNamespace = "")
        MciRequest arg0);

}
